AcmeTestBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeTestBundle:Default:index }

AcmeTestBundle_post:
    resource: "@AcmeTestBundle/Resources/config/routing/post.yml"
    prefix:   /post

AcmeTestBundle_comment:
    resource: "@AcmeTestBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

