parameters:
#    simple_admin_generator.example.class: Simple\AdminGeneratorBundle\Example
     simple_admin_generator:
          theme :  default
services:
#    simple_admin_generator.example:
#        class: %simple_admin_generator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

